"""End-to-end pipeline: discover URLs -> fetch+parse each -> write JSON, XML sitemap, frontend data."""
from __future__ import annotations

import io
import json
import sys
import time
from dataclasses import asdict
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, ElementTree
from xml.dom import minidom

from . import discover, parse

# Force UTF-8 on Windows so the console doesn't blow up on é/è/ô etc.
if sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "out"
HTML_CACHE = OUT / "html"
JSON_DIR = OUT / "json"
WEB = ROOT / "web"
WEB_DATA = WEB / "recipes.json"
WEB_DATA_JS = WEB / "recipes-data.js"   # window.RECIPES = [...] for the buildless React app
SITEMAP = WEB / "sitemap.xml"

for d in (OUT, HTML_CACHE, JSON_DIR, WEB):
    d.mkdir(parents=True, exist_ok=True)


def run(force_refetch: bool = False, throttle: float = 0.5) -> None:
    # 1. discover
    per_source = discover.discover_all()
    discover.summarize(per_source)
    urls = sorted(set().union(*per_source.values()))

    # write discovery audit
    (OUT / "discovery.json").write_text(
        json.dumps({k: sorted(v) for k, v in per_source.items()} | {"union": urls}, indent=2),
        encoding="utf-8",
    )

    # 2. fetch + parse (cached by id) via the rich showRecipePageData blob
    print(f"\n[build] fetching + parsing {len(urls)} URLs (cache={'OFF' if force_refetch else 'ON'})")
    records: list[dict] = []
    seen_ids: set[str] = set()   # dedupe: one recipe id can appear under several URL slugs
    skipped = 0
    dupes = 0
    for i, url in enumerate(urls, 1):
        rid, _, _ = parse.parse_id(url)
        if not rid:
            print(f"  [{i:>3}/{len(urls)}] SKIP (no id): {url}")
            continue
        if rid in seen_ids:
            dupes += 1
            continue
        html_path = HTML_CACHE / f"{rid}.html"
        try:
            if html_path.exists() and not force_refetch:
                html = html_path.read_text(encoding="utf-8")
                src = "cache"
            else:
                from .http import get
                html = get(url)
                html_path.write_text(html, encoding="utf-8")
                src = "net"
                time.sleep(throttle)
            rec = parse.parse_show_data(url, html)
        except Exception as e:
            print(f"  [{i:>3}/{len(urls)}] FAIL {url}: {e}")
            continue
        if not rec or not rec.get("title"):
            skipped += 1
            continue
        # per-recipe JSON (local reference copy)
        (JSON_DIR / f"{rid}.json").write_text(
            json.dumps(rec, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        records.append(rec)
        seen_ids.add(rid)
        if i % 40 == 0 or i == len(urls):
            print(f"  [{i:>3}/{len(urls)}] {src:5s} S{str(rec.get('season') or '?'):>2}  {(rec.get('title') or '?')[:50]}")

    # 3. sort by season desc (newest first), then title; write frontend data
    records.sort(key=lambda r: (-(r.get("season") or 0), (r.get("title") or "").lower()))
    WEB_DATA.write_text(json.dumps(records, indent=2, ensure_ascii=False), encoding="utf-8")
    WEB_DATA_JS.write_text(
        "// Auto-generated by masterchef.build — do not edit.\n"
        "window.RECIPES = " + json.dumps(records, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )

    # 4. emit a proper sitemap.xml for our own site
    from xml.etree import ElementTree as ET
    urlset = Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    for r in records:
        u = SubElement(urlset, "url")
        SubElement(u, "loc").text = r["url"]
        lastmod = parse.air_date_from_id(r["url"])
        if lastmod:
            SubElement(u, "lastmod").text = lastmod
    pretty = minidom.parseString(ET.tostring(urlset, encoding="utf-8")).toprettyxml(indent="  ")
    SITEMAP.write_text(pretty, encoding="utf-8")

    # 5. summary
    from collections import Counter
    seasons = Counter(r.get("season") for r in records)
    chefs = Counter(r.get("chef") for r in records if r.get("chef"))
    courses = Counter(r.get("course") for r in records)
    print(f"\n[build] DONE")
    print(f"  recipes:    {len(records)}  (skipped {skipped} blob-less, {dupes} dup-id URLs)")
    print(f"  seasons:    {dict(sorted(seasons.items(), key=lambda kv: (kv[0] is None, kv[0] or 0)))}")
    print(f"  courses:    {dict(courses)}")
    print(f"  chefs:      {len(chefs)} (top 5: {chefs.most_common(5)})")
    print(f"  frontend data: {WEB_DATA_JS}  ({WEB_DATA_JS.stat().st_size/1024:.1f} KB)")
    print(f"  sitemap:       {SITEMAP}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--refetch", action="store_true", help="Bypass HTML cache and re-fetch")
    args = ap.parse_args()
    run(force_refetch=args.refetch)
