// Auto-generated by masterchef.build. Set GA_ID in masterchef/seo.py.
(function(){
  var ID = "G-XXXXXXXXXX";
  if (!ID || ID.indexOf("XXXX") >= 0) return;   // no-op until a real GA4 ID is set
  var s = document.createElement('script'); s.async = true;
  s.src = "https://www.googletagmanager.com/gtag/js?id=" + ID;
  document.head.appendChild(s);
  window.dataLayer = window.dataLayer || [];
  window.gtag = function(){ dataLayer.push(arguments); };
  gtag('js', new Date());
  gtag('config', ID);
})();
